name: Ubuntu 22.04 DXFImportPlugin

on:
  # run nightly at 2:00 am

  # allow to be triggered on github webpage manually
  workflow_dispatch:
  # run whenever someone pushes data
  # WARNING: this may give excessive build times which need to be paid!
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: install qt6
      run: sudo apt install qt6-base-dev qt6-svg-dev libgl1-mesa-dev
    - name: link submodule libraries
      working-directory: externals
      run: ./createLinuxSymlinks.sh
    - name: build
      working-directory: build/cmake
      run: ./build.sh release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DXFImportPlugin_Ubuntu2204
        path: bin/release/*.so
