name: Windows VC2019 DxfImportPlugin Complete

on:
  # run nightly at 4:00 am
#  schedule:
#    - cron: "0 4 * * *"
  # allow to be triggered on github webpage manually
  workflow_dispatch:
  # run whenever someone pushes data
  # WARNING: this may give excessive build times which need to be paid!
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install jom
      run: choco install jom -y
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 16  # Visual Studio 2019 corresponds to version 16
    - name: install qt5
      uses: jurplel/install-qt-action@v4.0.0
      with:
        host: 'windows'
        target: 'desktop'
        install-deps: 'true'
        arch: win64_msvc2019_64
        archives: 'qtbase qtsvg'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
#        setup-python: 'true'
#        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        set-env: 'true'
        tools-only: 'false'
        aqtversion: '==3.1.*'
        py7zrversion: '==0.20.*'
        extra: '--external 7z'
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: create symlinks of submodules
      working-directory: externals
      shell: cmd
      run: createWindowsSoftlinks.bat
    - name: build
      working-directory: build/cmake/
      shell: cmd
      run: build_VC_x64.bat release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: DXFImportPlugin_win64
        path: bin\release_x64\*.dll
