name: Windows DxfImportPlugin Complete

on:
  # allow to be triggered on github webpage manually
  workflow_dispatch:
  # run whenever someone pushes data
  # WARNING: this may give excessive build times which need to be paid!
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install jom
      run: choco install jom -y

    - name: Install Visual Studio Build Tools
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    - name: install qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.2'
        host: 'windows'
        target: 'desktop'
        arch: win64_msvc2022_64
        archives: 'qtbase qtsvg'
        cache: 'true'
        set-env: 'true'

    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: build
      working-directory: build/cmake/
      shell: cmd
      run: build_VC_x64.bat release

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: DXFImportPlugin_win64
        path: bin\release_x64\*.dll
